# Generated by Django 4.2.30 on 2026-04-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_companyTM', models.CharField(max_length=100, verbose_name='Компания, проводящая ТО')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_component', models.CharField(max_length=100, verbose_name='Узел машины')),
            ],
        ),
        migrations.CreateModel(
            name='ControlledBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_controlled_bridge', models.CharField(max_length=100, verbose_name='Модель управляемого моста')),
                ('description_controlled_bridge', models.CharField(blank=True, max_length=250, verbose_name='Описание управляемого моста')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=100, unique=True, verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driving_bridge', models.CharField(max_length=100, verbose_name='Модель ведущего моста')),
                ('description_driving_bridge', models.CharField(blank=True, max_length=250, verbose_name='Оисание ведущего моста')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_machine', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер машины')),
                ('serial_number_engine', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер двигателя')),
                ('serial_number_transmission', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер трансмиссии')),
                ('serial_number_driving_bridge', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер ведущего моста')),
                ('serial_number_controlled_bridge', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер управляемого моста')),
                ('supply_contract_number_and_date', models.CharField(max_length=100, unique=True, verbose_name='Договор поставки номер и дата')),
                ('date_shipment_from_factory', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('recipient', models.CharField(max_length=100, verbose_name='Получатель')),
                ('operating_address', models.CharField(max_length=250, verbose_name='Эксплуатационный адрес')),
                ('equipment', models.CharField(max_length=250, verbose_name='Комплектация')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='maintenance_service.customers', verbose_name='Клиент')),
                ('model_controlled_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_bridges', to='maintenance_service.controlledbridge', verbose_name='Управляемый мост')),
                ('model_driving_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_bridges', to='maintenance_service.drivingbridge', verbose_name='Ведущий мост')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEngined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model_engine', models.CharField(max_length=100, verbose_name='Модель двигателя')),
                ('description_model_engine', models.CharField(blank=True, max_length=250, verbose_name='Описание двигателя')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model_machine', models.CharField(max_length=100, verbose_name='Модель машины')),
                ('description_model_machine', models.CharField(blank=True, max_length=250, verbose_name='Описание машины')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recovery_method', models.CharField(max_length=100, verbose_name='Способ восстановления')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service_company', models.CharField(max_length=100, unique=True, verbose_name='Сервисная компания')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_transmission', models.CharField(max_length=100, verbose_name='Модель трансмиссии')),
                ('description_transmission', models.CharField(blank=True, max_length=250, verbose_name='Описание трансмиссии')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfTechnicalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_of_TM', models.CharField(max_length=100, unique=True, verbose_name='Вид ТО')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tm', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(verbose_name='Наработка')),
                ('number_orderoutfit', models.CharField(max_length=100, unique=True, verbose_name='Номер заказ-наряда')),
                ('date_orderoutfit', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_machines', to='maintenance_service.machine', verbose_name='Машина')),
                ('serial_number_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_sn_machine', to='maintenance_service.machine', verbose_name='Серийный номер машины')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_companies', to='maintenance_service.servicecompanies', verbose_name='Сервисная компания')),
                ('tm_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_companies', to='maintenance_service.companiestm', verbose_name='Компания, проводившая ТО')),
                ('type_of_tm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='maintenance_service.typeoftechnicalmaintenance', verbose_name='Вид ТО')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='model_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='maintenance_service.modelengined', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='maintenance_service.modelmachines', verbose_name='Модель машины'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='maintenance_service.transmission', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_companies', to='maintenance_service.servicecompanies', verbose_name='Сервисная компания'),
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_failure', models.DateField(verbose_name='Дата отказа')),
                ('claim_operating_time', models.IntegerField(verbose_name='Наработка в момент обращения')),
                ('description_failure', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.CharField(max_length=250, verbose_name='Используемые запасные части')),
                ('date_recovery', models.DateField(verbose_name='Дата восстановления')),
                ('equipment_downtime', models.IntegerField(blank=True, null=True, verbose_name='Время простоя (дни)')),
                ('component_failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='maintenance_service.componentsmachine', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_machines', to='maintenance_service.machine', verbose_name='Машина')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='maintenance_service.recoverymethods', verbose_name='Способ восстановления')),
                ('serial_number_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_sn_machine', to='maintenance_service.machine', verbose_name='Серийный номер машины')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_service_companies', to='maintenance_service.servicecompanies', verbose_name='Сервисная компания')),
            ],
        ),
    ]
