# Generated by Django 4.2.30 on 2026-05-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_service', '0002_create_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='component_failure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='maintenance_service.componentsmachine', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_machines', to='maintenance_service.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='maintenance_service.recoverymethods', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='serial_number_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_sn_machine', to='maintenance_service.machine', verbose_name='Серийный номер машины'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_service_companies', to='maintenance_service.servicecompanies', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='maintenance_service.customers', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_controlled_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_bridges', to='maintenance_service.controlledbridge', verbose_name='Управляемый мост'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_driving_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_bridges', to='maintenance_service.drivingbridge', verbose_name='Ведущий мост'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='maintenance_service.modelengined', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='maintenance_service.modelmachines', verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='maintenance_service.transmission', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_companies', to='maintenance_service.servicecompanies', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_machines', to='maintenance_service.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='serial_number_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_sn_machine', to='maintenance_service.machine', verbose_name='Серийный номер машины'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_companies', to='maintenance_service.servicecompanies', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='tm_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_companies', to='maintenance_service.companiestm', verbose_name='Компания, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='type_of_tm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='maintenance_service.typeoftechnicalmaintenance', verbose_name='Вид ТО'),
        ),
    ]
