# Generated by Django 4.2.30 on 2026-05-20 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance_service', '0005_customerproxy_servicecompanyproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerproxy',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='servicecompanyproxy',
            options={'verbose_name': 'Service Company', 'verbose_name_plural': 'Service Companies'},
        ),
        migrations.RemoveField(
            model_name='technicalmaintenance',
            name='machine',
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='serial_number_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_sn_machine', to='maintenance_service.machine', verbose_name='Зав. номер машины'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'ServiceCompany'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_companies', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
