# Generated by Django 4.2.30 on 2026-05-20 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance_service', '0006_alter_customerproxy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claims',
            name='machine',
        ),
        migrations.AlterField(
            model_name='claims',
            name='claim_operating_time',
            field=models.IntegerField(verbose_name='Наработка в момент обращения (м.ч.)'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='component_failure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_components', to='maintenance_service.componentsmachine', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_methods', to='maintenance_service.recoverymethods', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='serial_number_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_sn_machine', to='maintenance_service.machine', verbose_name='Зав. номер машины'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'ServiceCompany'}, on_delete=django.db.models.deletion.CASCADE, related_name='claims_service_companies', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
